## Regex-Based Classification

In [1]:
import polars as pl

def classify_cancer_samples(df: pl.DataFrame) -> pl.DataFrame:
    """
    Classify samples as cancer / non-cancer / uncertain based on metadata text patterns.
    Returns the same DataFrame with added classification columns.
    """

    # --- Step 1: Setup --- look
    PRIORITY_COLS = ["source_name", "tissue", "phenotype", "disease", "cell_type", "tumor_type"]
    PRIORITY_COLS = [c for c in PRIORITY_COLS if c in df.columns]

    # Regex patterns
    CANCER_POS = r"(?:\bcancers?\b|\btumou?rs?\b|\bmalignan(?:t|cy)\b|\bcarcinomas?\b|\bneoplasms?\b|\bmetasta(?:s|t)es?\b|\badenocarcinomas?\b|\bsarcomas?\b|\bleukemi(?:a|as)\b|\blymphom(?:a|as)\b|\bglioblastomas?\b|\bmelanomas?\b|\boncolog(?:y|ic|ical)\b)"
    CANCER_NEG = r"(?:\bnormal\b|\bhealthy\b|\bctrl\b|\badjacent normal\b|\bnon[-\s]?tumou?r(?:al)?\b|\bbenign\b|\bnon[-\s]?cancer(?:ous)?\b|\bsham\b|\bunaffected\b)"
    ONCO_TRAPS = r"(?:\boncophora\b|\boncorhynchus\b|\boncotic\b|\boncomodulin\b)"

    # Helper to normalize text columns
    def normalize_text(col_expr):
        return (
            col_expr.cast(pl.Utf8)
            .fill_null("")
            .str.to_lowercase()
            .str.replace_all(r"[_/|]", " ")
            .str.replace_all(r"\s+", " ")
            .str.strip_chars()
        )

    # --- Step 2: Sample name detection ---
    sample_name_col = "title" if "title" in df.columns else "biosample"

    df = df.with_columns([
        normalize_text(pl.col(sample_name_col)).str.contains(CANCER_POS).alias("cancer_in_sample_name"),
        normalize_text(pl.col(sample_name_col)).str.contains(CANCER_NEG).alias("negative_in_sample_name"),
        normalize_text(pl.col(sample_name_col)).str.contains(ONCO_TRAPS).alias("onco_trap_in_sample_name"),
    ])

    # --- Step 3: Check priority columns ---
    for col in PRIORITY_COLS:
        df = df.with_columns([
            normalize_text(pl.col(col)).str.contains(CANCER_POS).alias(f"cancer_in_{col}"),
            normalize_text(pl.col(col)).str.contains(CANCER_NEG).alias(f"negative_in_{col}"),
        ])

    # --- Step 4: Count mentions ---
    cancer_mention_cols = [f"cancer_in_{c}" for c in PRIORITY_COLS]
    negative_mention_cols = [f"negative_in_{c}" for c in PRIORITY_COLS]

    df = df.with_columns([
        pl.sum_horizontal([pl.col(c) for c in cancer_mention_cols if c in df.columns]).alias("n_cancer_mentions"),
        pl.sum_horizontal([pl.col(c) for c in negative_mention_cols if c in df.columns]).alias("n_negative_mentions"),
    ])

    # --- Step 5: Confidence category ---
    df = df.with_columns([
        pl.when(pl.col("onco_trap_in_sample_name"))
        .then(pl.lit("uncertain_onco_trap"))
        .when(
            pl.col("cancer_in_sample_name") &
            (pl.col("n_cancer_mentions") >= 1) &
            (pl.col("n_negative_mentions") == 0)
        )
        .then(pl.lit("confident_cancer"))
        .when(
            (pl.col("cancer_in_sample_name") & (pl.col("n_negative_mentions") == 0)) |
            (pl.col("n_cancer_mentions") >= 2)
        )
        .then(pl.lit("likely_cancer"))
        .when(
            pl.col("negative_in_sample_name") |
            (pl.col("n_negative_mentions") >= 1)
        )
        .then(pl.lit("likely_non_cancer"))
        .when(pl.col("n_cancer_mentions") == 1)
        .then(pl.lit("uncertain_weak_signal"))
        .otherwise(pl.lit("uncertain_no_signal"))
        .alias("confidence_category")
    ])

    return df

## Load Data

In [4]:
full_dataset = pl.read_csv(
    "data/combined_metadata_noncancer_removed.csv",
    schema_overrides={"group": pl.Utf8},   # <- dict of {col_name: dtype}
    infer_schema_length=0,                  # scan entire file for other cols
)

df = pl.read_csv("data/train_test.csv")

In [5]:
df = df[["experiment_accession", "bioproject", "biosample", "sample_accession","run_accession", "is_cancer"]]

# idx = full_dataset.columns.index("cancer_type")

# full_dataset = full_dataset[full_dataset.columns[:idx+1]]

In [6]:
df.head()

# full_dataset.head()

shape: (5, 6)
┌──────────────────────┬─────────────┬──────────────┬──────────────────┬───────────────┬───────────┐
│ experiment_accession ┆ bioproject  ┆ biosample    ┆ sample_accession ┆ run_accession ┆ is_cancer │
│ ---                  ┆ ---         ┆ ---          ┆ ---              ┆ ---           ┆ ---       │
│ str                  ┆ str         ┆ str          ┆ str              ┆ str           ┆ i64       │
╞══════════════════════╪═════════════╪══════════════╪══════════════════╪═══════════════╪═══════════╡
│ SRX10489019          ┆ PRJNA718814 ┆ GSM5220969   ┆ SRS8615268       ┆ SRR14118670   ┆ 1         │
│ ERX1283444           ┆ PRJEB6455   ┆ SAMEA3724868 ┆ ERS1032017       ┆ ERR1211193    ┆ 0         │
│ SRX17708205          ┆ PRJNA884362 ┆ GSM6601021   ┆ SRS15238722      ┆ SRR21710838   ┆ 1         │
│ SRX4518392           ┆ PRJNA484951 ┆ GSM3323504   ┆ SRS3636903       ┆ SRR7655999    ┆ 0         │
│ SRX9364181           ┆ PRJNA671877 ┆ GSM4860401   ┆ SRS7586602       ┆ SRR12899131   ┆ 0         │
└──────────────────────┴─────────────┴──────────────┴──────────────────┴───────────────┴───────────┘

In [7]:
joined = full_dataset.join(
    df,
    on=["experiment_accession", "bioproject", "biosample", "sample_accession", "run_accession"],  # matching keys
    how="inner"  # keep only matching rows
)

## Do Prediction

In [8]:
predicted_df = classify_cancer_samples(joined)

In [9]:
# find the position of "cancer_type"
idx = predicted_df.columns.index("cancer_type")

# slice up to that column (inclusive)
cols_to_keep = predicted_df.columns[:idx + 1]

# add the two specific extra columns
cols_to_keep += ["source_name", "is_cancer", "confidence_category"]

predicted_df.select(cols_to_keep)

shape: (172, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ experimen ┆ experimen ┆ title     ┆ study_nam ┆ … ┆ cancer_ty ┆ source_na ┆ is_cancer ┆ confiden │
│ t_alias   ┆ t_accessi ┆ ---       ┆ e         ┆   ┆ pe        ┆ me        ┆ ---       ┆ ce_categ │
│ ---       ┆ on        ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ i64       ┆ ory      │
│ str       ┆ ---       ┆           ┆ str       ┆   ┆ str       ┆ str       ┆           ┆ ---      │
│           ┆ str       ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ena-EXPER ┆ ERX352605 ┆ Illumina  ┆ null      ┆ … ┆ carcinoma ┆ null      ┆ 0         ┆ likely_n │
│ IMENT-FUN ┆ 7         ┆ HiSeq     ┆           ┆   ┆           ┆           ┆           ┆ on_cance │
│ CTIONAL   ┆           ┆ 2500      ┆           ┆   ┆           ┆           ┆           ┆ r        │
│ GENO…     ┆           ┆ paired    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ end…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM486040 ┆ SRX936418 ┆ GSM486040 ┆ null      ┆ … ┆ tumor*    ┆ Fresh-fro ┆ 0         ┆ likely_n │
│ 0         ┆ 0         ┆ 0: Fresh- ┆           ┆   ┆           ┆ zen       ┆           ┆ on_cance │
│           ┆           ┆ frozen    ┆           ┆   ┆           ┆ canine    ┆           ┆ r        │
│           ┆           ┆ canin…    ┆           ┆   ┆           ┆ healthy   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ br…       ┆           ┆          │
│ GSM486040 ┆ SRX936418 ┆ GSM486040 ┆ null      ┆ … ┆ tumor*    ┆ Fresh-fro ┆ 0         ┆ likely_n │
│ 1         ┆ 1         ┆ 1: Fresh- ┆           ┆   ┆           ┆ zen       ┆           ┆ on_cance │
│           ┆           ┆ frozen    ┆           ┆   ┆           ┆ canine    ┆           ┆ r        │
│           ┆           ┆ canin…    ┆           ┆   ┆           ┆ healthy   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ br…       ┆           ┆          │
│ GSM300511 ┆ SRX139997 ┆ GSM300511 ┆ null      ┆ … ┆ bladder   ┆ Normal    ┆ 0         ┆ likely_n │
│ 1         ┆ 82        ┆ 1: D_Norm ┆           ┆   ┆ cancer    ┆ Urothelia ┆           ┆ on_cance │
│           ┆           ┆ al_Mucosa ┆           ┆   ┆           ┆ l cells   ┆           ┆ r        │
│           ┆           ┆ ; C…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM249835 ┆ SRX258189 ┆ GSM249835 ┆ null      ┆ … ┆ tumor*    ┆ hemangios ┆ 1         ┆ uncertai │
│ 7         ┆ 9         ┆ 7:        ┆           ┆   ┆           ┆ arcoma    ┆           ┆ n_no_sig │
│           ┆           ┆ CHAD-P9;  ┆           ┆   ┆           ┆           ┆           ┆ nal      │
│           ┆           ┆ Canis     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ lup…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ GSM318787 ┆ SRX420033 ┆ GSM318787 ┆ null      ┆ … ┆ rhabdomyo ┆ tumor     ┆ 1         ┆ uncertai │
│ 6         ┆ 4         ┆ 6: Rh30:  ┆           ┆   ┆ sarcoma   ┆           ┆           ┆ n_weak_s │
│           ┆           ┆ RH30_ENT; ┆           ┆   ┆           ┆           ┆           ┆ ignal    │
│           ┆           ┆ Mu…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM357314 ┆ SRX527294 ┆ GSM357314 ┆ null      ┆ … ┆ tumor*    ┆ cells     ┆ 1         ┆ likely_n │
│ 0         ┆ 6         ┆ 0: SAM243 ┆           ┆   ┆           ┆ sorted    ┆           ┆ on_cance │
│           ┆           ┆ 42223     ┆           ┆   ┆           ┆ from MC38 ┆           ┆ r        │
│           ┆           ┆ Macrop…   ┆           ┆   ┆           ┆ tumors    ┆           ┆          │
│ GSM357315 ┆ SRX527295 ┆ GSM357315 ┆ null      ┆ … ┆ tumor*    ┆ cells     ┆ 1         ┆ likely_n │
│ 0         ┆ 6         ┆ 0: SAM243 ┆           ┆   ┆           ┆ sorted    ┆           ┆ on_cance │
│           ┆           ┆ 42227     ┆           ┆   ┆           ┆ from MC38 ┆           ┆ r        │
│           ┆           ┆ Macrop…   ┆           ┆   ┆           ┆ tumors    ┆           ┆          │
│ GSM361182 ┆ SRX538990 ┆ GSM361182 ┆ null      ┆ … ┆ tumor*    ┆ 4T1 tumor ┆ 1         ┆ confiden │
│ 3         ┆ 0         ┆ 3: Tumor  ┆           ┆   ┆           ┆           ┆           ┆ t_cancer │
│           ┆           ┆ 5_non-PoE ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Ms;…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ GSM403702 ┆ SRX672076 ┆ GSM403702 ┆ null      ┆ … ┆ hepatocel ┆ Tumor     ┆ 1         ┆ likely_c │
│ 9         ┆ 4         ┆ 9: MYC_Tw ┆           ┆   ┆ lular     ┆ tissue    ┆           ┆ ancer    │
│           ┆           ┆ ist1_HCC_ ┆           ┆   ┆ cancer    ┆           ┆           ┆          │
│           ┆           ┆ 5; …      ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [10]:
    # Create sample_id if it doesn't exist (use sample_accession as unique identifier)
if "sample_id" not in predicted_df.columns:
    predicted_df = predicted_df.with_columns(
        pl.col("sample_accession").alias("sample_id")
    )

uncertain_df = predicted_df.filter(
    pl.col("confidence_category").is_in(["uncertain_no_signal", "uncertain_weak_signal", "likely_non_cancer"])
)

## Define Cancer Rules

In [11]:
import medspacy
from medspacy.ner import TargetRule
from medspacy.target_matcher import TargetMatcher

nlp = medspacy.load(enable=["ner", "context"])
tm = nlp.get_pipe("medspacy_target_matcher")

rules = [
    # General cancer terms
    TargetRule(
        literal="cancer",
        category="CANCER",
        pattern=[{"LOWER": "cancer"}]
    ),
    TargetRule(
        literal="tumor",
        category="CANCER",
        pattern=[{"LOWER": {"IN": ["tumor", "tumour", "tumors", "tumours"]}}]
    ),
    TargetRule(
        literal="carcinoma",
        category="CANCER",
        pattern=[{"LOWER": {"REGEX": "carcinomas?"}}]
    ),
    
    # Specific cancer types
    TargetRule(
        literal="adenocarcinoma",
        category="CANCER",
        pattern=[{"LOWER": {"REGEX": "adenocarcinomas?"}}]
    ),
    TargetRule(
        literal="squamous cell carcinoma",
        category="CANCER",
        pattern=[
            {"LOWER": "squamous"},
            {"LOWER": "cell"},
            {"LOWER": {"REGEX": "carcinomas?"}}
        ]
    ),
    TargetRule(
        literal="small cell carcinoma",
        category="CANCER",
        pattern=[
            {"LOWER": "small"},
            {"LOWER": "cell"},
            {"LOWER": {"REGEX": "carcinomas?"}}
        ]
    ),
    TargetRule(
        literal="non-small cell carcinoma",
        category="CANCER",
        pattern=[
            {"LOWER": "non"},
            {"IS_PUNCT": True, "OP": "?"},  # optional hyphen
            {"LOWER": "small"},
            {"LOWER": "cell"},
            {"LOWER": {"REGEX": "carcinomas?"}}
        ]
    ),
    
    # Leukemia/Lymphoma
    TargetRule(
        literal="leukemia",
        category="CANCER",
        pattern=[{"LOWER": {"REGEX": "leuk[ae]mias?"}}]
    ),
    TargetRule(
        literal="lymphoma",
        category="CANCER",
        pattern=[{"LOWER": {"REGEX": "lymphomas?"}}]
    ),
    TargetRule(
        literal="acute myeloid leukemia",
        category="CANCER",
        pattern=[
            {"LOWER": "acute"},
            {"LOWER": "myeloid"},
            {"LOWER": {"REGEX": "leuk[ae]mias?"}}
        ]
    ),
    
    # Sarcomas
    TargetRule(
        literal="sarcoma",
        category="CANCER",
        pattern=[{"LOWER": {"REGEX": "sarcomas?"}}]
    ),
    TargetRule(
        literal="osteosarcoma",
        category="CANCER",
        pattern=[{"LOWER": {"REGEX": "osteosarcomas?"}}]
    ),
    
    # Brain tumors
    TargetRule(
        literal="glioblastoma",
        category="CANCER",
        pattern=[{"LOWER": {"REGEX": "glioblastomas?"}}]
    ),
    TargetRule(
        literal="glioma",
        category="CANCER",
        pattern=[{"LOWER": {"REGEX": "gliomas?"}}]
    ),
    
    # Melanoma
    TargetRule(
        literal="melanoma",
        category="CANCER",
        pattern=[{"LOWER": {"REGEX": "melanomas?"}}]
    ),
    
    # Malignancy terms
    TargetRule(
        literal="malignant",
        category="CANCER",
        pattern=[{"LOWER": {"REGEX": r"(?<!pre[- ])malignan(t|cy)"}}]
    ),

    TargetRule(
        literal="neoplasm",
        category="CANCER",
        pattern=[{"LOWER": {"REGEX": "neoplasms?"}}]
    ),
    TargetRule(
        literal="metastasis",
        category="CANCER",
        pattern=[{"LOWER": {"REGEX": "metasta(sis|ses|tic)"}}]
    ),
    
    # Context-dependent patterns (adjective + tissue)
    TargetRule(
        literal="malignant tissue",
        category="CANCER",
        pattern=[
            {"LOWER": "malignant"},
            {"LOWER": {"IN": ["tissue", "cells", "lesion", "mass"]}}
        ]
    ),
    TargetRule(
        literal="cancerous tissue",
        category="CANCER",
        pattern=[
            {"LOWER": "cancerous"},
            {"LOWER": {"IN": ["tissue", "cells", "lesion", "mass"]}}
        ]
    ),
    
    # Oncology context
    TargetRule(
        literal="oncology",
        category="CANCER",
        pattern=[{"LOWER": {"REGEX": "oncolog(y|ic|ical)"}}],
        # This one might need more context checking
    ),
    
    # Cell line patterns (common in research)
    TargetRule(
        literal="cancer cell line",
        category="CANCER",
        pattern=[
            {"LOWER": {"IN": ["cancer", "tumor", "tumour"]}},
            {"LOWER": "cell"},
            {"LOWER": {"IN": ["line", "lines"]}}
        ]
    ),

    TargetRule(
        literal="TIL",
        category="CANCER",
        pattern=[
            {"LOWER": {"IN": ["til", "tils", "t-i-l", "t.i.l.", "t.i.l.s."]}},
            {"LOWER": {"IN": ["tumor", "tumour"]}, "OP": "?"},
            {"LOWER": {"IN": ["infiltrating", "infiltrated"]}, "OP": "?"},
            {"LOWER": "lymphocytes", "OP": "?"},
        ]
    )

]

tm.add(rules)

## Define non-cancer rules

In [12]:
non_cancer_rules = [
    TargetRule(
        literal="normal tissue",
        category="NON_CANCER",
        pattern=[
            {"LOWER": {"IN": ["normal", "healthy", "control", "benign", "adjacent"]}},
            {"LOWER": {"IN": ["tissue", "sample", "cells", "fat", "pad", "organ"]}, "OP": "?"}
        ]
    ),

    TargetRule(
        literal="benign lesion",
        category="NON_CANCER",
        pattern=[
            {"LOWER": "benign"},
            {"LOWER": {"IN": ["lesion", "mass", "tumor", "tumour"]}}
        ]
    ),

    TargetRule(
    literal="premalignant",
    category="NON_CANCER",
    pattern=[{"LOWER": {"REGEX": "pre[- ]?malignan(t|cy)"}}]
    )

]

tm.add(non_cancer_rules)

## MedSpacy Helper Funcs

In [13]:
def medspacy_classify(row_texts):
    cancer_found = False
    non_cancer_found = False
    negation_found = False

    for text in row_texts:
        doc = nlp(text)
        for ent in doc.ents:
            if ent.label_ == "CANCER":
                if ent._.is_negated:
                    negation_found = True
                else:
                    cancer_found = True
            elif ent.label_ == "NON_CANCER":
                if not ent._.is_negated:
                    non_cancer_found = True

    # Decision hierarchy
    if cancer_found and not negation_found:
        return "CANCER"
    elif non_cancer_found and not cancer_found:
        return "NOT_CANCER"
    elif cancer_found and non_cancer_found:
        return "UNCERTAIN"
    elif negation_found:
        return "NOT_CANCER"
    else:
        return "NO_SIGNAL"


UNCERTAIN_LABELS = [
    "uncertain_no_signal",
    "uncertain_weak_signal"
]

def clean_texts(row):
    texts = [
        str(row[col]).strip()
        for col in ["source_name", "tissue", "phenotype", "disease"]
        if col in row and row[col] not in (None, "None", "nan", "NaN", "", "null")
    ]
    return texts


def resolve_uncertain(regex_label: str, med_label: str | None) -> str:
    if med_label is None:
        return regex_label

    if regex_label in UNCERTAIN_LABELS:
        if med_label == "CANCER":
            return "confirmed_by_medspacy"
        elif med_label == "NOT_CANCER":
            return "confirmed_non_cancer"
        elif med_label == "UNCERTAIN":
            return "uncertain_medspacy"
        else:
            return regex_label

    # Confident non-cancer but medspacy says otherwise — flip if strong contradiction
    if regex_label == "likely_non_cancer" and med_label == "CANCER":
        return "confirmed_by_medspacy"

    return regex_label

## Run the MedSpacy on each of my rows of interests

In [14]:
# uncertain_df = uncertain_df.filter(pl.col("source_name") == "Mus musculus CD8 TILs")

In [15]:
results = []

for row in uncertain_df.iter_rows(named=True):
    texts = clean_texts(row)
    if texts:  # skip empty rows
        result = medspacy_classify(texts)
    else:
        result = "NO_SIGNAL"
    results.append(result)

2025-11-16 13:54:38.613 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=0] [doc 0] Token 0 'Fresh' marked as sentence start (span begin)
2025-11-16 13:54:38.613 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=0] Token/tag mapping: [(Fresh, True), (-, False), (frozen, False), (canine, False), (healthy, False), (brain, False), (tissue, False)]
2025-11-16 13:54:38.614 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2025-11-16 13:54:38.615 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=1] Token/tag mapping: [(nan, True), (control, False), (nan, False), (nan, False), (control, False), (nan, False)]
2025-11-16 13:54:38.616 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2] [doc 0] Token 0 'Fresh' marked as sentence start (span begin)
2025-11-16 13:54:38.616 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=2] Token/tag mapping: [(Fresh, True), (-, False), (frozen, False), (canine, False), (healthy, False), (brain, False), (tissue, False)]
2025-11-16 13:54:38.617 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2025-11-16 13:54:38.617 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=3] Token/tag mapping: [(nan, True), (control, False), (nan, False), (nan, False), (control, False), (nan, False)]
2025-11-16 13:54:38.618 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=4] [doc 0] Token 0 'Normal' marked as sentence start (span begin)
2025-11-16 13:54:38.618 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=4] Token/tag mapping: [(Normal, True), (Urothelial, False), (cells, False)]
2025-11-16 13:54:38.619 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=5] [doc 0] Token 0 'Bladder' marked as sentence start (span begin)
2025-11-16 13:54:38.619 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=5] Token/tag mapping: [(Bladder, True)]
2025-11-16 13:54:38.619 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=6] [doc 0] Token 0 'hemangiosarcoma' marked as sentence start (span begin)
2025-11-16 13:54:38.620 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=6] Token/tag mapping: [(hemangiosarcoma, True)]
2025-11-16 13:54:38.620 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2025-11-16 13:54:38.621 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=7] Token/tag mapping: [(nan, True), (spleen, False), (nan, False), (nan, False), (spleen, False), (nan, False)]
2025-11-16 13:54:38.621 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=8] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2025-11-16 13:54:38.622 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=8] Token/tag mapping: [(canine, True), (mammary, False), (normal, False), (tissue, False)]
2025-11-16 13:54:38.622 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=9] [doc 0] Token 0 'mammary' marked as sentence start (span begin)
2025-11-16 13:54:38.622 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=9] Token/tag mapping: [(mammary, True), (normal, False), (tissue, False)]
2025-11-16 13:54:38.623 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=10] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2025-11-16 13:54:38.624 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=10] Token/tag mapping: [(canine, True), (mammary, False), (normal, False), (tissue, False)]
2025-11-16 13:54:38.624 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=11] [doc 0] Token 0 'mammary' marked as sentence start (span begin)
2025-11-16 13:54:38.624 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=11] Token/tag mapping: [(mammary, True), (normal, False), (tissue, False)]
2025-11-16 13:54:38.625 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=12] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2025-11-16 13:54:38.625 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=12] Token/tag mapping: [(canine, True), (mammary, False), (normal, False), (tissue, False)]
2025-11-16 13:54:38.626 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=13] [doc 0] Token 0 'mammary' marked as sentence start (span begin)
2025-11-16 13:54:38.627 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=13] Token/tag mapping: [(mammary, True), (normal, False), (tissue, False)]
2025-11-16 13:54:38.628 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=14] [doc 0] Token 0 'canine' marked as sentence start (span begin)
2025-11-16 13:54:38.628 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=14] Token/tag mapping: [(canine, True), (simple, False), (mammary, False), (carcinoma, False)]
2025-11-16 13:54:38.630 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=15] [doc 0] Token 0 'Untreated' marked as sentence start (span begin)
2025-11-16 13:54:38.630 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=15] Token/tag mapping: [(Untreated, True), (PC12, False), (cells, False), (from, False), (pheochromocytoma, False), (of, False), (the, False), (rat, False), (adrenal, False), (medulla, False), (were, False), (sampled, False)]
2025-11-16 13:54:38.631 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=16] [doc 0] Token 0 'Primary' marked as sentence start (span begin)
2025-11-16 13:54:38.631 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=16] Token/tag mapping: [(Primary, True), (murine, False), (osteosarcomas, False)]
2025-11-16 13:54:38.632 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=17] [doc 0] Token 0 'Primary' marked as sentence start (span begin)
2025-11-16 13:54:38.632 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=17] Token/tag mapping: [(Primary, True), (tumor, False)]
2025-11-16 13:54:38.632 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=18] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2025-11-16 13:54:38.633 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=18] Token/tag mapping: [(nan, True), (nan, False), (nan, False), (nan, False)]
2025-11-16 13:54:38.634 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=19] [doc 0] Token 0 'human' marked as sentence start (span begin)
2025-11-16 13:54:38.634 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=19] Token/tag mapping: [(human, True), (tumor, False), (necrosis, False), (factor, False), (expression, False)]
2025-11-16 13:54:38.635 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=20] [doc 0] Token 0 'rheumatoid' marked as sentence start (span begin)
2025-11-16 13:54:38.635 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=20] Token/tag mapping: [(rheumatoid, True), (arthritis, False)]
2025-11-16 13:54:38.635 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=21] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2025-11-16 13:54:38.636 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=21] Token/tag mapping: [(nan, True), (nan, False), (nan, False), (nan, False)]
2025-11-16 13:54:38.636 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=22] [doc 0] Token 0 'wild' marked as sentence start (span begin)
2025-11-16 13:54:38.636 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=22] Token/tag mapping: [(wild, True), (type, False)]
2025-11-16 13:54:38.637 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=23] [doc 0] Token 0 'glioblastoma' marked as sentence start (span begin)
2025-11-16 13:54:38.637 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=23] Token/tag mapping: [(glioblastoma, True), (multiforme, False)]
2025-11-16 13:54:38.638 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=24] [doc 0] Token 0 'normal' marked as sentence start (span begin)
2025-11-16 13:54:38.638 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=24] Token/tag mapping: [(normal, True), (brain, False)]
2025-11-16 13:54:38.639 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=25] [doc 0] Token 0 'normal' marked as sentence start (span begin)
2025-11-16 13:54:38.639 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=25] Token/tag mapping: [(normal, True), (brain, False), (nan, False), (normal, False), (brain, False), (nan, False)]
2025-11-16 13:54:38.639 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=26] [doc 0] Token 0 'CT26' marked as sentence start (span begin)
2025-11-16 13:54:38.640 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=26] Token/tag mapping: [(CT26, True), (cells, False)]
2025-11-16 13:54:38.640 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=27] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2025-11-16 13:54:38.641 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=27] Token/tag mapping: [(nan, True), (nan, False), (nan, False), (nan, False)]
2025-11-16 13:54:38.641 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=28] Token/tag mapping: [(4T1, False)]
2025-11-16 13:54:38.641 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=29] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2025-11-16 13:54:38.642 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=29] Token/tag mapping: [(nan, True), (nan, False), (nan, False), (nan, False)]
2025-11-16 13:54:38.642 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=30] [doc 0] Token 0 'Br53T2' marked as sentence start (span begin)
2025-11-16 13:54:38.642 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=30] Token/tag mapping: [(Br53T2, True)]
2025-11-16 13:54:38.643 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=31] [doc 0] Token 0 'Mammary' marked as sentence start (span begin)
2025-11-16 13:54:38.644 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=31] Token/tag mapping: [(Mammary, True), (tumor, False), (nan, False), (Mammary, False), (tumor, False), (nan, False)]
2025-11-16 13:54:38.644 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=32] [doc 0] Token 0 'RPM' marked as sentence start (span begin)
2025-11-16 13:54:38.644 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=32] Token/tag mapping: [(RPM, True), (-, False), (CAS9, False), (GEMM, False)]
2025-11-16 13:54:38.645 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=33] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2025-11-16 13:54:38.645 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=33] Token/tag mapping: [(nan, True), (nan, False), (nan, False), (nan, False)]
2025-11-16 13:54:38.646 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=34] [doc 0] Token 0 'Ht1080' marked as sentence start (span begin)
2025-11-16 13:54:38.647 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=34] Token/tag mapping: [(Ht1080, True), (tumor, False), (model, False), (_, False), (IgG1, False), (antibody, False), (treatment, False), (_, False), (WAT, False)]
2025-11-16 13:54:38.648 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=35] [doc 0] Token 0 'White' marked as sentence start (span begin)
2025-11-16 13:54:38.648 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=35] Token/tag mapping: [(White, True), (Adipose, False), (Tissue, False), (nan, False), (White, False), (Adipose, False), (Tissue, False), (nan, False)]
2025-11-16 13:54:38.649 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=36] [doc 0] Token 0 'Normal' marked as sentence start (span begin)
2025-11-16 13:54:38.649 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=36] Token/tag mapping: [(Normal, True), (mammary, False), (fat, False), (pad, False)]
2025-11-16 13:54:38.651 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=37] [doc 0] Token 0 'Normal' marked as sentence start (span begin)
2025-11-16 13:54:38.651 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=37] Token/tag mapping: [(Normal, True), (mammary, False), (fat, False), (pad, False), (nan, False), (Normal, False), (mammary, False), (fat, False), (pad, False), (nan, False)]
2025-11-16 13:54:38.652 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=38] [doc 0] Token 0 'Normal' marked as sentence start (span begin)
2025-11-16 13:54:38.652 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=38] Token/tag mapping: [(Normal, True), (mammary, False), (fat, False), (pad, False)]
2025-11-16 13:54:38.653 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=39] [doc 0] Token 0 'Normal' marked as sentence start (span begin)
2025-11-16 13:54:38.653 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=39] Token/tag mapping: [(Normal, True), (mammary, False), (fat, False), (pad, False), (nan, False), (Normal, False), (mammary, False), (fat, False), (pad, False), (nan, False)]
2025-11-16 13:54:38.654 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=40] [doc 0] Token 0 'fallopian' marked as sentence start (span begin)
2025-11-16 13:54:38.655 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=40] Token/tag mapping: [(fallopian, True), (tube, False), (tissue, False)]
2025-11-16 13:54:38.656 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=41] [doc 0] Token 0 'premalignant' marked as sentence start (span begin)
2025-11-16 13:54:38.656 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=41] Token/tag mapping: [(premalignant, True), (stage, False), (fallopian, False), (tubes, False)]
2025-11-16 13:54:38.657 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=42] [doc 0] Token 0 'Mouse' marked as sentence start (span begin)
2025-11-16 13:54:38.657 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=42] Token/tag mapping: [(Mouse, True), (backskin, False)]
2025-11-16 13:54:38.658 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=43] [doc 0] Token 0 'Skin' marked as sentence start (span begin)
2025-11-16 13:54:38.658 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=43] Token/tag mapping: [(Skin, True), (nan, False), (Skin, False), (nan, False)]
2025-11-16 13:54:38.659 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=44] [doc 0] Token 0 'B16' marked as sentence start (span begin)
2025-11-16 13:54:38.659 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=44] Token/tag mapping: [(B16, True), (melanoma, False), (-, False), (in, False), (vitro, False)]
2025-11-16 13:54:38.660 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=45] [doc 0] Token 0 'nan' marked as sentence start (span begin)
2025-11-16 13:54:38.660 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=45] Token/tag mapping: [(nan, True), (nan, False), (nan, False), (nan, False)]
2025-11-16 13:54:38.660 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=46] [doc 0] Token 0 'macrophage' marked as sentence start (span begin)
2025-11-16 13:54:38.661 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=46] Token/tag mapping: [(macrophage, True)]
2025-11-16 13:54:38.661 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=47] [doc 0] Token 0 'tumor' marked as sentence start (span begin)
2025-11-16 13:54:38.661 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=47] Token/tag mapping: [(tumor, True), (nan, False), (tumor, False), (nan, False)]
2025-11-16 13:54:38.662 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=48] [doc 0] Token 0 'small' marked as sentence start (span begin)
2025-11-16 13:54:38.663 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=48] Token/tag mapping: [(small, True), (cell, False), (lung, False), (cancer, False), (cells, False)]
2025-11-16 13:54:38.663 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=49] Token/tag mapping: [(lung, False)]
2025-11-16 13:54:38.664 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=50] [doc 0] Token 0 'Normal' marked as sentence start (span begin)
2025-11-16 13:54:38.664 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=50] Token/tag mapping: [(Normal, True), (stomach, False), (fibroblasts, False)]
2025-11-16 13:54:38.664 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=51] [doc 0] Token 0 'Stomach' marked as sentence start (span begin)
2025-11-16 13:54:38.665 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=51] Token/tag mapping: [(Stomach, True)]
2025-11-16 13:54:38.665 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=52] [doc 0] Token 0 'Neuro' marked as sentence start (span begin)
2025-11-16 13:54:38.665 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=52] Token/tag mapping: [(Neuro, True), (-, False), (2a, False), (_, False), (WT, False), (_, False), (DMSO, False), (2hrs, False)]
2025-11-16 13:54:38.666 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=53] [doc 0] Token 0 'Glioblastoma' marked as sentence start (span begin)
2025-11-16 13:54:38.666 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=53] Token/tag mapping: [(Glioblastoma, True), (single, False), (cell, False)]
2025-11-16 13:54:38.667 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=54] [doc 0] Token 0 'macrophage' marked as sentence start (span begin)
2025-11-16 13:54:38.667 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=54] Token/tag mapping: [(macrophage, True), (single, False), (cell, False)]
2025-11-16 13:54:38.668 | DEBUG    | PyRuSH.PyRuSHSentencizer:predict:100 - [cpredict_split_gaps|call_id=55] [doc 0] Token 0 'No' marked as sentence start (span begin)

In [16]:
uncertain_df = uncertain_df.with_columns(pl.Series("medspacy_detected_cancer", results))

In [17]:
uncertain_df.select(['source_name', 'medspacy_detected_cancer'])

shape: (110, 2)
┌─────────────────────────────────┬──────────────────────────┐
│ source_name                     ┆ medspacy_detected_cancer │
│ ---                             ┆ ---                      │
│ str                             ┆ str                      │
╞═════════════════════════════════╪══════════════════════════╡
│ null                            ┆ NO_SIGNAL                │
│ Fresh-frozen canine healthy br… ┆ NOT_CANCER               │
│ Fresh-frozen canine healthy br… ┆ NOT_CANCER               │
│ Normal Urothelial cells         ┆ NOT_CANCER               │
│ hemangiosarcoma                 ┆ CANCER                   │
│ …                               ┆ …                        │
│ WT mammary gland                ┆ NO_SIGNAL                │
│ Rosa26LSL-Sox2-IRES-GFP;Lkb1fl… ┆ NO_SIGNAL                │
│ tumor                           ┆ CANCER                   │
│ cells sorted from MC38 tumors   ┆ CANCER                   │
│ cells sorted from MC38 tumors   ┆ CANCER                   │
└─────────────────────────────────┴──────────────────────────┘

In [18]:
uncertain_df = uncertain_df.unique(subset=["run_accession"], keep="first")

predicted_df = predicted_df.join(
    uncertain_df.select(["run_accession", "medspacy_detected_cancer"]),
    on=["run_accession"],
    how="left",
)

In [19]:
predicted_df.select(['source_name', 'medspacy_detected_cancer'])

shape: (172, 2)
┌─────────────────────────────────┬──────────────────────────┐
│ source_name                     ┆ medspacy_detected_cancer │
│ ---                             ┆ ---                      │
│ str                             ┆ str                      │
╞═════════════════════════════════╪══════════════════════════╡
│ null                            ┆ NO_SIGNAL                │
│ Fresh-frozen canine healthy br… ┆ NOT_CANCER               │
│ Fresh-frozen canine healthy br… ┆ NOT_CANCER               │
│ Normal Urothelial cells         ┆ NOT_CANCER               │
│ hemangiosarcoma                 ┆ CANCER                   │
│ …                               ┆ …                        │
│ tumor                           ┆ CANCER                   │
│ cells sorted from MC38 tumors   ┆ CANCER                   │
│ cells sorted from MC38 tumors   ┆ CANCER                   │
│ 4T1 tumor                       ┆ null                     │
│ Tumor tissue                    ┆ null                     │
└─────────────────────────────────┴──────────────────────────┘

In [20]:
predicted_df = predicted_df.with_columns(
    pl.struct(["confidence_category", "medspacy_detected_cancer"])
    .map_elements(
        lambda row: resolve_uncertain(
            row["confidence_category"], row["medspacy_detected_cancer"]
        ),
        return_dtype=pl.Utf8,
    )
    .alias("final_classification")
)

In [21]:
# find the position of "cancer_type"
idx = predicted_df.columns.index("cancer_type")

# slice up to that column (inclusive)
# cols_to_keep = predicted_df.columns[:idx + 1]
cols_to_keep = ["experiment_alias", "source_name", "tissue", "phenotype", "disease"]


# add the two specific extra columns
cols_to_keep += ["is_cancer", "final_classification", "medspacy_detected_cancer"]

In [22]:
predicted_df.select(cols_to_keep)

shape: (172, 8)
┌────────────┬────────────┬────────────┬───────────┬─────────┬───────────┬────────────┬────────────┐
│ experiment ┆ source_nam ┆ tissue     ┆ phenotype ┆ disease ┆ is_cancer ┆ final_clas ┆ medspacy_d │
│ _alias     ┆ e          ┆ ---        ┆ ---       ┆ ---     ┆ ---       ┆ sification ┆ etected_ca │
│ ---        ┆ ---        ┆ str        ┆ str       ┆ str     ┆ i64       ┆ ---        ┆ ncer       │
│ str        ┆ str        ┆            ┆           ┆         ┆           ┆ str        ┆ ---        │
│            ┆            ┆            ┆           ┆         ┆           ┆            ┆ str        │
╞════════════╪════════════╪════════════╪═══════════╪═════════╪═══════════╪════════════╪════════════╡
│ ena-EXPERI ┆ null       ┆ null       ┆ null      ┆ null    ┆ 0         ┆ likely_non ┆ NO_SIGNAL  │
│ MENT-FUNCT ┆            ┆            ┆           ┆         ┆           ┆ _cancer    ┆            │
│ IONAL      ┆            ┆            ┆           ┆         ┆           ┆            ┆            │
│ GENO…      ┆            ┆            ┆           ┆         ┆           ┆            ┆            │
│ GSM4860400 ┆ Fresh-froz ┆ nan        ┆ null      ┆ null    ┆ 0         ┆ likely_non ┆ NOT_CANCER │
│            ┆ en canine  ┆ control    ┆           ┆         ┆           ┆ _cancer    ┆            │
│            ┆ healthy    ┆ nan nan    ┆           ┆         ┆           ┆            ┆            │
│            ┆ br…        ┆ control    ┆           ┆         ┆           ┆            ┆            │
│            ┆            ┆ na…        ┆           ┆         ┆           ┆            ┆            │
│ GSM4860401 ┆ Fresh-froz ┆ nan        ┆ null      ┆ null    ┆ 0         ┆ likely_non ┆ NOT_CANCER │
│            ┆ en canine  ┆ control    ┆           ┆         ┆           ┆ _cancer    ┆            │
│            ┆ healthy    ┆ nan nan    ┆           ┆         ┆           ┆            ┆            │
│            ┆ br…        ┆ control    ┆           ┆         ┆           ┆            ┆            │
│            ┆            ┆ na…        ┆           ┆         ┆           ┆            ┆            │
│ GSM3005111 ┆ Normal     ┆ Bladder    ┆ null      ┆ null    ┆ 0         ┆ likely_non ┆ NOT_CANCER │
│            ┆ Urothelial ┆            ┆           ┆         ┆           ┆ _cancer    ┆            │
│            ┆ cells      ┆            ┆           ┆         ┆           ┆            ┆            │
│ GSM2498357 ┆ hemangiosa ┆ nan spleen ┆ null      ┆ null    ┆ 1         ┆ confirmed_ ┆ CANCER     │
│            ┆ rcoma      ┆ nan nan    ┆           ┆         ┆           ┆ by_medspac ┆            │
│            ┆            ┆ spleen nan ┆           ┆         ┆           ┆ y          ┆            │
│ …          ┆ …          ┆ …          ┆ …         ┆ …       ┆ …         ┆ …          ┆ …          │
│ GSM3187876 ┆ tumor      ┆ alveolar   ┆ null      ┆ null    ┆ 1         ┆ confirmed_ ┆ CANCER     │
│            ┆            ┆ rhabdomyos ┆           ┆         ┆           ┆ by_medspac ┆            │
│            ┆            ┆ arcoma     ┆           ┆         ┆           ┆ y          ┆            │
│ GSM3573140 ┆ cells      ┆ nan nan    ┆ null      ┆ null    ┆ 1         ┆ confirmed_ ┆ CANCER     │
│            ┆ sorted     ┆ nan nan    ┆           ┆         ┆           ┆ by_medspac ┆            │
│            ┆ from MC38  ┆            ┆           ┆         ┆           ┆ y          ┆            │
│            ┆ tumors     ┆            ┆           ┆         ┆           ┆            ┆            │
│ GSM3573150 ┆ cells      ┆ nan nan    ┆ null      ┆ null    ┆ 1         ┆ confirmed_ ┆ CANCER     │
│            ┆ sorted     ┆ nan nan    ┆           ┆         ┆           ┆ by_medspac ┆            │
│            ┆ from MC38  ┆            ┆           ┆         ┆           ┆ y          ┆            │
│            ┆ tumors     ┆            ┆           ┆         ┆           ┆            ┆            │
│ GSM3611823 ┆ 4T1 tumor  ┆ nan nan    ┆ null      ┆ null    ┆ 1         ┆ confident_ ┆ null       │
│            ┆            ┆ nan nan    ┆           ┆         ┆           ┆ cancer     ┆            │
│ GSM4037029 ┆ Tumor      ┆ hepatocell ┆ null      ┆ null    ┆ 1         ┆ likely_can ┆ null       │
│            ┆ tissue     ┆ ular       ┆           ┆         ┆           ┆ cer        ┆            │
│            ┆            ┆ carcinoma  ┆           ┆         ┆           ┆            ┆            │
└────────────┴────────────┴────────────┴───────────┴─────────┴───────────┴────────────┴────────────┘

In [23]:
predicted_df_filtered = (
    predicted_df
    .filter(pl.col("final_classification") == "confirmed_by_medspacy")
    .select(cols_to_keep)
)

predicted_df_filtered

shape: (29, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ experiment ┆ source_nam ┆ tissue     ┆ phenotype ┆ disease   ┆ is_cancer ┆ final_cla ┆ medspacy_ │
│ _alias     ┆ e          ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ssificati ┆ detected_ │
│ ---        ┆ ---        ┆ str        ┆ str       ┆ str       ┆ i64       ┆ on        ┆ cancer    │
│ str        ┆ str        ┆            ┆           ┆           ┆           ┆ ---       ┆ ---       │
│            ┆            ┆            ┆           ┆           ┆           ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ GSM2498357 ┆ hemangiosa ┆ nan spleen ┆ null      ┆ null      ┆ 1         ┆ confirmed ┆ CANCER    │
│            ┆ rcoma      ┆ nan nan    ┆           ┆           ┆           ┆ _by_medsp ┆           │
│            ┆            ┆ spleen nan ┆           ┆           ┆           ┆ acy       ┆           │
│ GSM3993105 ┆ canine     ┆ null       ┆ null      ┆ null      ┆ 1         ┆ confirmed ┆ CANCER    │
│            ┆ simple     ┆            ┆           ┆           ┆           ┆ _by_medsp ┆           │
│            ┆ mammary    ┆            ┆           ┆           ┆           ┆ acy       ┆           │
│            ┆ carcinom…  ┆            ┆           ┆           ┆           ┆           ┆           │
│ GSM5957075 ┆ Primary    ┆ Primary    ┆ null      ┆ null      ┆ 1         ┆ confirmed ┆ CANCER    │
│ _r1        ┆ murine ost ┆ tumor      ┆           ┆           ┆           ┆ _by_medsp ┆           │
│            ┆ eosarcomas ┆            ┆           ┆           ┆           ┆ acy       ┆           │
│ E-MTAB-727 ┆ null       ┆ nan nan    ┆ human     ┆ rheumatoi ┆ 0         ┆ confirmed ┆ CANCER    │
│ 9:Sample   ┆            ┆ nan nan    ┆ tumor     ┆ d         ┆           ┆ _by_medsp ┆           │
│ 11_s       ┆            ┆            ┆ necrosis  ┆ arthritis ┆           ┆ acy       ┆           │
│            ┆            ┆            ┆ factor    ┆           ┆           ┆           ┆           │
│            ┆            ┆            ┆ ex…       ┆           ┆           ┆           ┆           │
│ E-MTAB-935 ┆ null       ┆ null       ┆ wild type ┆ glioblast ┆ 1         ┆ confirmed ┆ CANCER    │
│ 3:17038-00 ┆            ┆            ┆           ┆ oma multi ┆           ┆ _by_medsp ┆           │
│ 23_s       ┆            ┆            ┆           ┆ forme     ┆           ┆ acy       ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ GSM3119932 ┆ Tumor      ┆ null       ┆ null      ┆ null      ┆ 1         ┆ confirmed ┆ CANCER    │
│            ┆ B16F10     ┆            ┆           ┆           ┆           ┆ _by_medsp ┆           │
│            ┆ melanoma   ┆            ┆           ┆           ┆           ┆ acy       ┆           │
│ GSM3142052 ┆ mice brain ┆ null       ┆ null      ┆ null      ┆ 1         ┆ confirmed ┆ CANCER    │
│            ┆ tumors     ┆            ┆           ┆           ┆           ┆ _by_medsp ┆           │
│            ┆            ┆            ┆           ┆           ┆           ┆ acy       ┆           │
│ GSM3187876 ┆ tumor      ┆ alveolar   ┆ null      ┆ null      ┆ 1         ┆ confirmed ┆ CANCER    │
│            ┆            ┆ rhabdomyos ┆           ┆           ┆           ┆ _by_medsp ┆           │
│            ┆            ┆ arcoma     ┆           ┆           ┆           ┆ acy       ┆           │
│ GSM3573140 ┆ cells      ┆ nan nan    ┆ null      ┆ null      ┆ 1         ┆ confirmed ┆ CANCER    │
│            ┆ sorted     ┆ nan nan    ┆           ┆           ┆           ┆ _by_medsp ┆           │
│            ┆ from MC38  ┆            ┆           ┆           ┆           ┆ acy       ┆           │
│            ┆ tumors     ┆            ┆           ┆           ┆           ┆           ┆           │
│ GSM3573150 ┆ cells      ┆ nan nan    ┆ null      ┆ null      ┆ 1         ┆ confirmed ┆ CANCER    │
│            ┆ sorted     ┆ nan nan    ┆           ┆           ┆           ┆ _by_medsp ┆           │
│            ┆ from MC38  ┆            ┆           ┆           ┆           ┆ acy       ┆           │
│            ┆ tumors     ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

## Looking @ Accuracy

In [ ]:
# Validation: Compare predictions against ground truth
validation_summary = (
    predicted_df
    .group_by("final_classification", "is_cancer")
    .agg(pl.count().alias("count"))
    .sort("final_classification", "is_cancer")
)

print("=== Classification vs Ground Truth ===")
print(validation_summary)

# Calculate accuracy for confident predictions
confident_predictions = predicted_df.filter(
    pl.col("final_classification").is_in(["confident_cancer", "confirmed_by_medspacy"])
)

if len(confident_predictions) > 0:
    correct = confident_predictions.filter(pl.col("is_cancer") == True).height
    total = confident_predictions.height
    accuracy = correct / total * 100
    print(f"\nAccuracy on confident cancer predictions: {accuracy:.1f}% ({correct}/{total})")

# Check non-cancer predictions
non_cancer_predictions = predicted_df.filter(
    pl.col("final_classification").is_in(["likely_non_cancer", "confirmed_non_cancer"])
)

if len(non_cancer_predictions) > 0:
    correct_non = non_cancer_predictions.filter(pl.col("is_cancer") == False).height
    total_non = non_cancer_predictions.height
    accuracy_non = correct_non / total_non * 100
    print(f"Accuracy on non-cancer predictions: {accuracy_non:.1f}% ({correct_non}/{total_non})")

In [ ]:
test_samples = [
    ["breast cancer tissue"],
    ["normal breast tissue"],
    ["no evidence of tumor"],
    ["benign lesion no malignancy"],
    ["metastatic carcinoma"],
    ["healthy control sample"],
    ["previous cancer but resolved"],
    ["adjacent non-tumor tissue"],
    ["Normal mammary fat pad nan Normal mammary fat pad nan"],
    ["null"],
    ["Mus musculus CD8 TILs"],
    ["premalignant stage fallopian tubes"]
]

In [ ]:
for texts in test_samples:
    result = medspacy_classify(texts)
    print(f"{texts[0]:35s} → {result}")

In [ ]:
for row in uncertain_df.iter_rows(named=True):
    texts = clean_texts(row)
    result = medspacy_classify(texts)
    if "TILs" in str(texts):
        print(row["sample_id"], "texts:", texts, "→", result)

## Getting all the Terms from disease row in full dataset

In [ ]:
all_samples = pl.read_csv(
    "data/combined_metadata_noncancer_removed.csv",
    schema_overrides={"group": pl.Utf8},   # <- dict of {col_name: dtype}
    infer_schema_length=0,                  # scan entire file for other cols
)

In [ ]:
unique_diseases = all_samples.select("disease").unique().to_series().to_list()

# TODO: add "cancer_type" - keep the NON_CANCER from disease & base CANCER rules from cancer_type

In [ ]:
len(unique_diseases)

In [ ]:
unique_diseases

## Autogenerate some TargetRules for our list of unique diseases

In [ ]:
## Auto-generate TargetRules for diseases

KEYWORDS_CANCER = (
    "cancer",
    "carcinoma",
    "sarcoma",
    "leuk",
    "lymphoma",
    "tumor",
    "tumour",
    "melanoma",
    "blastoma",
    "myeloma",
    "metast",
)

_skip_literals = {rule.literal.lower() for rule in (rules + non_cancer_rules)}


def _phrase_to_pattern(phrase: str):
    doc = nlp.make_doc(phrase.lower())
    pattern = []
    for token in doc:
        if token.is_space:
            continue
        if token.is_alpha:
            pattern.append({"LOWER": token.lower_})
        elif token.is_digit:
            pattern.append({"LIKE_NUM": True})
        elif token.is_punct:
            pattern.append({"TEXT": token.text})
        else:
            pattern.append({"LOWER": token.lower_})
    return pattern


auto_rules = []
skipped_literals = []

for disease in unique_diseases:
    if disease is None:
        continue
    disease_str = str(disease).strip()
    if not disease_str or disease_str.lower() in {"nan", "none", "null"}:
        continue
    norm_literal = disease_str.lower()
    if norm_literal in _skip_literals:
        skipped_literals.append(disease_str)
        continue
    pattern = _phrase_to_pattern(disease_str)
    if not pattern:
        continue
    category = (
        "CANCER"
        if any(keyword in norm_literal for keyword in KEYWORDS_CANCER)
        else "NON_CANCER"
    )
    auto_rules.append(
        TargetRule(
            literal=disease_str,
            category=category,
            pattern=pattern,
        )
    )

if auto_rules:
    tm.add(auto_rules)

print(f"Added {len(auto_rules)} disease rules, skipped {len(skipped_literals)} existing literals.")

In [ ]:
for r in tm.rules:
    if r.category == "NON_CANCER":
        print(r.literal)

In [ ]:
# Existing TargetRules
# skipped_literals

In [ ]:
predicted_df = classify_cancer_samples(all_samples)

In [ ]:
# find the position of "cancer_type"
idx = predicted_df.columns.index("cancer_type")

# slice up to that column (inclusive)
cols_to_keep = predicted_df.columns[:idx + 1]

# add the two specific extra columns
cols_to_keep += ["source_name", "confidence_category"]

predicted_df.select(cols_to_keep)

# Create sample_id if it doesn't exist (use sample_accession as unique identifier)
if "sample_id" not in predicted_df.columns:
    predicted_df = predicted_df.with_columns(
        pl.col("sample_accession").alias("sample_id")
    )

uncertain_df = predicted_df.filter(
    pl.col("confidence_category").is_in(["uncertain_no_signal", "uncertain_weak_signal", "likely_non_cancer"])
)

results = []

for row in uncertain_df.iter_rows(named=True):
    texts = clean_texts(row)
    if texts:  # skip empty rows
        result = medspacy_classify(texts)
    else:
        result = "NO_SIGNAL"
    results.append(result)

uncertain_df = uncertain_df.with_columns(pl.Series("medspacy_detected_cancer", results))

uncertain_df = uncertain_df.unique(subset=["run_accession"], keep="first")

predicted_df = predicted_df.join(
    uncertain_df.select(["run_accession", "medspacy_detected_cancer"]),
    on=["run_accession"],
    how="left",
)

In [ ]:
predicted_df = predicted_df.with_columns(
    pl.struct(["confidence_category", "medspacy_detected_cancer"])
    .map_elements(
        lambda row: resolve_uncertain(
            row["confidence_category"], row["medspacy_detected_cancer"]
        ),
        return_dtype=pl.Utf8,
    )
    .alias("final_classification")
)

In [ ]:
# find the position of "cancer_type"
idx = predicted_df.columns.index("cancer_type")

# slice up to that column (inclusive)
# cols_to_keep = predicted_df.columns[:idx + 1]
cols_to_keep = ["experiment_alias", "source_name", "tissue", "phenotype", "disease"]


# add the two specific extra columns
cols_to_keep += ["final_classification", "medspacy_detected_cancer"]

predicted_df.select(cols_to_keep)

predicted_df_filtered = (
    predicted_df
    .filter(pl.col("final_classification") == "confirmed_by_medspacy")
    .select(cols_to_keep)
)

predicted_df_filtered